[workspace]
# Project metadata and basic configuration
authors = ["University of Washington Scientific Software Engineering Center"] # Project authors
channels = ["conda-forge"] # Conda channels for dependencies
name = "project-template" # Project name
platforms = ["osx-arm64"] # Supported platforms for development and deployment
version = "0.1.0" # Project version

# The environment configurations for different development scenarios
[environments]
default = { features = ["pre-commit", "gh-cli"], solve-group = "default" } # The default development environment with pre-commit and GitHub CLI
onboard = { features = ["pre-commit", "gh-cli", "onboard"], solve-group = "default" } # The onboarding environment with additional setup tasks

# The project dependencies
[dependencies]

# The project dependencies from PyPI
[pypi-dependencies]

# The main project tasks
[tasks]

# GitHub CLI feature for interacting with GitHub from the command line
[feature.gh-cli.dependencies]
gh = ">=2.0.0"

# Pre-commit feature for code quality and consistency
[feature.pre-commit.dependencies]
pre-commit = ">=4.3.0"

[feature.pre-commit.tasks]
pre-commit-install = { cmd = "pre-commit install", description = "Install pre-commit hooks in the git repository" }
pre-commit-all = { cmd = "pre-commit run --all-files", description = "Run pre-commit checks on all files" }
pre-commit = { cmd = "pre-commit run", description = "Run pre-commit checks on staged files" }

# Onboarding feature for setting up the development environment
[feature.onboard.pypi-dependencies]
ssec-cli = { git = "https://github.com/uw-ssec/ssec-cli.git" }

[feature.onboard.tasks]
ssec-setup = { cmd = "ssec --install-completion", description = "Set up shell completion for ssec-cli" }
onboard = { cmd = "ssec onboard", description = "Run the onboarding process for the SSEC project", depends-on = [
    "pre-commit-install",
    "ssec-setup",
] }
